name: betzac
version: 0.1.0.0
github: "betza-lang/betzac"
license: GPL-3
author: "Thierry Poulin"
maintainer: "thierry.poulin@icloud.com"
copyright: "2026 Thierry Poulin"

extra-source-files:
  - README.md
  - CHANGELOG.md

data-files:
  - prelude/std.betza

# Metadata used when publishing your package
synopsis:            Betzac is a compiler of betza notation, a description language for esoteric chess variants.
category:            Compiler, Game 

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/betza-lang/betzac#readme>

dependencies:
  - base >= 4.7 && < 5
  - transformers
  - text
  - lens
  - lsp
  - megaparsec
  - containers
  - directory
  - filepath

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  betzac:
    main: Main.hs
    source-dirs: app/Betzac
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - betzac
      - optparse-applicative
  bls:
    main: Main.hs
    source-dirs: app/Bls
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - betzac

tests:
  betzac-test:
    main: Spec.hs
    source-dirs: test/Betzac
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - QuickCheck
      - hedgehog
      - hspec-hedgehog
      - betzac
      - temporary
      - directory
      - filepath
  bls-test:
    main: Spec.hs
    source-dirs: test/Bls
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - betzac
      - hspec
      - lsp-test
      - temporary
      - directory
      - filepath
