{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}

module Betzac.AST.Types.Constraints (
    EqX,
    ShowX,
    DataX,
    WalkX,
    SpanX,
    OriginX,
) where

import Betzac.Span (HasSpan)

import Betzac.AST.Generic (WalkField)
import Betzac.AST.Origin (HasOrigin)
import Betzac.AST.Types.Ext
import Data.Data (Data, Typeable)

-- Eq, Show, and Data
type EqX p =
    ( Eq (XOverride p)
    , Eq (XPlain p)
    , Eq (XUsing p)
    , Eq (XExport p)
    , Eq (XBare p)
    , Eq (XAssign p)
    , Eq (XLabelRef p)
    , Eq (XBetzaExpr p)
    , Eq (XChainExpr p)
    , Eq (XChainLeg p)
    , Eq (XUnionExpr p)
    , Eq (XModifierExpr p)
    , Eq (XExponentExpr p)
    , Eq (XParen p)
    , Eq (XFrom p)
    , Eq (XDirectional p)
    , Eq (XBehavioural p)
    , Eq (XAmalgamated p)
    , Eq (XSingle p)
    , Eq (XForward p)
    , Eq (XBackward p)
    , Eq (XLeftward p)
    , Eq (XRightward p)
    , Eq (XSideway p)
    , Eq (XVertically p)
    , Eq (XAll p)
    , Eq (XBehaviour p)
    , Eq (XCapture p)
    , Eq (XLeap p)
    , Eq (XInitial p)
    , Eq (XJump p)
    , Eq (XMove p)
    , Eq (XNoJump p)
    , Eq (XHop p)
    , Eq (XOnce p)
    , Eq (XTwice p)
    , Eq (XAny p)
    , Eq (XChainOperator p)
    , Eq (XStep p)
    , Eq (XSequence p)
    , Eq (XMandatory p)
    , Eq (XIffUnblocked p)
    , Eq (XChoose p)
    , Eq (XExponent p)
    , Eq (XInfinite p)
    , Eq (XSlippery p)
    , Eq (XRepeat p)
    , Eq (XUpper p)
    , Eq (XDescriptor p)
    , Eq (XLeaper p)
    , Eq (XQualification p)
    , Eq (XJoint p)
    )

type ShowX p =
    ( Show (XOverride p)
    , Show (XPlain p)
    , Show (XUsing p)
    , Show (XExport p)
    , Show (XBare p)
    , Show (XAssign p)
    , Show (XLabelRef p)
    , Show (XBetzaExpr p)
    , Show (XChainExpr p)
    , Show (XChainLeg p)
    , Show (XUnionExpr p)
    , Show (XModifierExpr p)
    , Show (XExponentExpr p)
    , Show (XParen p)
    , Show (XFrom p)
    , Show (XDirectional p)
    , Show (XBehavioural p)
    , Show (XAmalgamated p)
    , Show (XSingle p)
    , Show (XForward p)
    , Show (XBackward p)
    , Show (XLeftward p)
    , Show (XRightward p)
    , Show (XSideway p)
    , Show (XVertically p)
    , Show (XAll p)
    , Show (XBehaviour p)
    , Show (XCapture p)
    , Show (XLeap p)
    , Show (XInitial p)
    , Show (XJump p)
    , Show (XMove p)
    , Show (XNoJump p)
    , Show (XHop p)
    , Show (XOnce p)
    , Show (XTwice p)
    , Show (XAny p)
    , Show (XChainOperator p)
    , Show (XStep p)
    , Show (XSequence p)
    , Show (XMandatory p)
    , Show (XIffUnblocked p)
    , Show (XChoose p)
    , Show (XExponent p)
    , Show (XInfinite p)
    , Show (XSlippery p)
    , Show (XRepeat p)
    , Show (XUpper p)
    , Show (XDescriptor p)
    , Show (XLeaper p)
    , Show (XQualification p)
    , Show (XJoint p)
    )

type DataX p =
    ( Typeable p
    , Data p
    , Data (XOverride p)
    , Data (XPlain p)
    , Data (XUsing p)
    , Data (XExport p)
    , Data (XBare p)
    , Data (XAssign p)
    , Data (XLabelRef p)
    , Data (XBetzaExpr p)
    , Data (XChainExpr p)
    , Data (XChainLeg p)
    , Data (XUnionExpr p)
    , Data (XModifierExpr p)
    , Data (XExponentExpr p)
    , Data (XParen p)
    , Data (XFrom p)
    , Data (XDirectional p)
    , Data (XBehavioural p)
    , Data (XAmalgamated p)
    , Data (XSingle p)
    , Data (XForward p)
    , Data (XBackward p)
    , Data (XLeftward p)
    , Data (XRightward p)
    , Data (XSideway p)
    , Data (XVertically p)
    , Data (XAll p)
    , Data (XBehaviour p)
    , Data (XCapture p)
    , Data (XLeap p)
    , Data (XInitial p)
    , Data (XJump p)
    , Data (XMove p)
    , Data (XNoJump p)
    , Data (XHop p)
    , Data (XOnce p)
    , Data (XTwice p)
    , Data (XAny p)
    , Data (XChainOperator p)
    , Data (XStep p)
    , Data (XSequence p)
    , Data (XMandatory p)
    , Data (XIffUnblocked p)
    , Data (XChoose p)
    , Data (XExponent p)
    , Data (XInfinite p)
    , Data (XSlippery p)
    , Data (XRepeat p)
    , Data (XUpper p)
    , Data (XDescriptor p)
    , Data (XLeaper p)
    , Data (XQualification p)
    , Data (XJoint p)
    )

-- Generic traversal
type WalkX p =
    ( Typeable p
    , WalkField (XOverride p)
    , WalkField (XPlain p)
    , WalkField (XUsing p)
    , WalkField (XExport p)
    , WalkField (XBare p)
    , WalkField (XAssign p)
    , WalkField (XLabelRef p)
    , WalkField (XBetzaExpr p)
    , WalkField (XChainExpr p)
    , WalkField (XChainLeg p)
    , WalkField (XUnionExpr p)
    , WalkField (XModifierExpr p)
    , WalkField (XExponentExpr p)
    , WalkField (XParen p)
    , WalkField (XFrom p)
    , WalkField (XDirectional p)
    , WalkField (XBehavioural p)
    , WalkField (XAmalgamated p)
    , WalkField (XSingle p)
    , WalkField (XForward p)
    , WalkField (XBackward p)
    , WalkField (XLeftward p)
    , WalkField (XRightward p)
    , WalkField (XSideway p)
    , WalkField (XVertically p)
    , WalkField (XAll p)
    , WalkField (XBehaviour p)
    , WalkField (XCapture p)
    , WalkField (XLeap p)
    , WalkField (XInitial p)
    , WalkField (XJump p)
    , WalkField (XMove p)
    , WalkField (XNoJump p)
    , WalkField (XHop p)
    , WalkField (XOnce p)
    , WalkField (XTwice p)
    , WalkField (XAny p)
    , WalkField (XChainOperator p)
    , WalkField (XStep p)
    , WalkField (XSequence p)
    , WalkField (XMandatory p)
    , WalkField (XIffUnblocked p)
    , WalkField (XChoose p)
    , WalkField (XExponent p)
    , WalkField (XInfinite p)
    , WalkField (XSlippery p)
    , WalkField (XRepeat p)
    , WalkField (XUpper p)
    , WalkField (XDescriptor p)
    , WalkField (XLeaper p)
    , WalkField (XQualification p)
    , WalkField (XJoint p)
    )

-- HasSpan
type SpanX p =
    ( HasSpan (XOverride p)
    , HasSpan (XPlain p)
    , HasSpan (XUsing p)
    , HasSpan (XExport p)
    , HasSpan (XBare p)
    , HasSpan (XAssign p)
    , HasSpan (XLabelRef p)
    , HasSpan (XBetzaExpr p)
    , HasSpan (XChainExpr p)
    , HasSpan (XChainLeg p)
    , HasSpan (XUnionExpr p)
    , HasSpan (XModifierExpr p)
    , HasSpan (XExponentExpr p)
    , HasSpan (XParen p)
    , HasSpan (XFrom p)
    , HasSpan (XChainOperator p)
    , HasSpan (XStep p)
    , HasSpan (XSequence p)
    , HasSpan (XMandatory p)
    , HasSpan (XChoose p)
    , HasSpan (XIffUnblocked p)
    , HasSpan (XDirectional p)
    , HasSpan (XBehavioural p)
    , HasSpan (XAmalgamated p)
    , HasSpan (XSingle p)
    , HasSpan (XForward p)
    , HasSpan (XBackward p)
    , HasSpan (XLeftward p)
    , HasSpan (XRightward p)
    , HasSpan (XSideway p)
    , HasSpan (XVertically p)
    , HasSpan (XAll p)
    , HasSpan (XBehaviour p)
    , HasSpan (XCapture p)
    , HasSpan (XLeap p)
    , HasSpan (XInitial p)
    , HasSpan (XJump p)
    , HasSpan (XMove p)
    , HasSpan (XNoJump p)
    , HasSpan (XHop p)
    , HasSpan (XOnce p)
    , HasSpan (XTwice p)
    , HasSpan (XAny p)
    , HasSpan (XExponent p)
    , HasSpan (XInfinite p)
    , HasSpan (XSlippery p)
    , HasSpan (XRepeat p)
    , HasSpan (XUpper p)
    , HasSpan (XDescriptor p)
    , HasSpan (XLeaper p)
    )

{- | The nodes a desugaring can supply or find already written. Statements,
expressions, atoms and labels are never synthesised, so they are absent here.
-}
type OriginX p =
    ( HasOrigin (XAmalgamated p)
    , HasOrigin (XSingle p)
    , HasOrigin (XForward p)
    , HasOrigin (XBackward p)
    , HasOrigin (XLeftward p)
    , HasOrigin (XRightward p)
    , HasOrigin (XSideway p)
    , HasOrigin (XVertically p)
    , HasOrigin (XAll p)
    , HasOrigin (XBehaviour p)
    , HasOrigin (XCapture p)
    , HasOrigin (XLeap p)
    , HasOrigin (XInitial p)
    , HasOrigin (XJump p)
    , HasOrigin (XMove p)
    , HasOrigin (XNoJump p)
    , HasOrigin (XHop p)
    , HasOrigin (XOnce p)
    , HasOrigin (XTwice p)
    , HasOrigin (XAny p)
    , HasOrigin (XChainOperator p)
    , HasOrigin (XStep p)
    , HasOrigin (XSequence p)
    , HasOrigin (XMandatory p)
    , HasOrigin (XChoose p)
    , HasOrigin (XIffUnblocked p)
    )
